version: '3.8'

services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    environment:
      - NODE_ENV=production
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=secret
      - SQUID_HOST=squid
      - SQUID_PORT=3128
    depends_on:
      - squid
    restart: unless-stopped

  squid:
    image: ubuntu/squid:latest
    ports:
      - "3128:3128"
    volumes:
      - ./squid/squid.conf:/etc/squid/squid.conf:ro
      - ./squid/passwords:/etc/squid/passwords:ro
      - squid_cache:/var/spool/squid
    restart: unless-stopped

volumes:
  squid_cache: