version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    environment:
      - NODE_ENV=production
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=secret
    restart: unless-stopped

  squid:
    build:
      context: .
      dockerfile: Dockerfile.squid
    ports:
      - "3128:3128"
    volumes:
      - ./squid/squid.conf:/etc/squid/squid.conf:ro
      - ./squid/rewriter:/usr/local/squid/rewriter:ro
      - squid_cache:/var/spool/squid
      - squid_logs:/var/log/squid
    environment:
      - PROXY_USER=arturojkl
      - PROXY_PASS=HQKxDbtCiC
      - PROXY_HOST=45.166.110.64
      - PROXY_HTTP_PORT=50100
      - PROXY_SOCKS_PORT=50101
    restart: unless-stopped

volumes:
  squid_cache:
  squid_logs: