version: '3.8'

services:
  proxy:
    build:
      context: .
      dockerfile: docker/proxy/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    environment:
      - NODE_ENV=production
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=secret
      - BARE_SERVER_PORT=8080
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - proxy
    restart: unless-stopped

  bare:
    build:
      context: .
      dockerfile: docker/bare/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    restart: unless-stopped