version: '3.8'

services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    environment:
      - NODE_ENV=production
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=secret
    restart: unless-stopped

  squid:
    build:
      context: .
      dockerfile: Dockerfile.squid
    ports:
      - "3128:3128"
    volumes:
      - ./squid/squid.conf:/etc/squid/squid.conf:ro
      - squid_cache:/var/spool/squid
      - squid_logs:/var/log/squid
      - squid_run:/var/run/squid
    environment:
      - TZ=UTC
    depends_on:
      - proxy
    restart: unless-stopped
    user: proxy

volumes:
  squid_cache:
  squid_logs:
  squid_run: