version: '3.8'

services:
  proxy:
    image: squid
    ports:
      - "3128:3128"
    volumes:
      - ./squid.conf:/etc/squid/squid.conf:ro
    restart: unless-stopped

  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    environment:
      - SE_NODE_MAX_SESSIONS=10
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    restart: unless-stopped